# Generated by Django 6.0.1 on 2026-01-21 04:42

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters.')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(unique=True, validators=[projects.models.validate_slug]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters.')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be at least 2 characters.')]),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='author_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Comment cannot be empty.')]),
        ),
    ]
